package menu;

import DAO.LoaiMonAnDAO;
import DAO.MonAnDAO;
import TienIch.Auth;
import TienIch.MsgBox;
import TienIch.XImage;
import entity.LoaiMonAn;
import entity.MonAn;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tan thien
 */
public class frmSanPham extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmSanPham
     */
    public frmSanPham() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonAn = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblHinhAnh = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtMaMonAn = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTenMonAn = new javax.swing.JTextField();
        txtGiaTien = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cboTenLoaiMon = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        txtMaLoaiMon1 = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoaiMonAn = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMonAnChung = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        btnXoa1 = new javax.swing.JButton();
        txtMaLoaiMon = new javax.swing.JTextField();
        txtTenLoaiMon = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        btnLuu1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        txtShowMonAn = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btnThem1 = new javax.swing.JButton();

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));

        jPanel6.setBackground(new java.awt.Color(153, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTimKiem.setBackground(new java.awt.Color(153, 255, 204));
        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.setText("Tìm kiếm theo tên món !");
        txtTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
        });
        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtTimKiemMouseReleased(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/timkiem.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblMonAn.setBackground(new java.awt.Color(0, 255, 204));
        tblMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ MÓN", "TÊN MÓN", "MÃ LOẠI", "GIÁ TIỀN", "HÌNH ẢNH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonAn.setRowHeight(30);
        tblMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMonAn);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTimKiem)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(153, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Thông tin món:");

        lblHinhAnh.setBackground(new java.awt.Color(51, 51, 51));
        lblHinhAnh.setForeground(new java.awt.Color(0, 0, 0));
        lblHinhAnh.setText("Hình ảnh");
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lblHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhAnhMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Mã món:");

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Mã loại món:");

        txtMaMonAn.setBackground(new java.awt.Color(153, 255, 204));
        txtMaMonAn.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtMaMonAn.setForeground(new java.awt.Color(0, 0, 0));
        txtMaMonAn.setText("0");
        txtMaMonAn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Tên món:");

        txtTenMonAn.setBackground(new java.awt.Color(153, 255, 204));
        txtTenMonAn.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtTenMonAn.setForeground(new java.awt.Color(0, 0, 0));
        txtTenMonAn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtGiaTien.setBackground(new java.awt.Color(153, 255, 204));
        txtGiaTien.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtGiaTien.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Giá tiền:");

        cboTenLoaiMon.setBackground(new java.awt.Color(153, 255, 204));
        cboTenLoaiMon.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        cboTenLoaiMon.setForeground(new java.awt.Color(0, 0, 0));
        cboTenLoaiMon.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cboTenLoaiMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenLoaiMonActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Tên loại món:");

        txtMaLoaiMon1.setBackground(new java.awt.Color(153, 255, 204));
        txtMaLoaiMon1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtMaLoaiMon1.setForeground(new java.awt.Color(0, 0, 0));
        txtMaLoaiMon1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSua.setBackground(new java.awt.Color(102, 102, 102));
        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(102, 102, 102));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/luu.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(102, 102, 102));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(102, 102, 102));
        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboTenLoaiMon, 0, 357, Short.MAX_VALUE)
                                    .addComponent(txtGiaTien)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(txtMaLoaiMon1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenMonAn, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMaMonAn)))))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel12)
                        .addGap(47, 47, 47)
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtMaLoaiMon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cboTenLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnLuu)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("MÓN ĂN", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 255, 204));

        jPanel12.setBackground(new java.awt.Color(153, 255, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("QUẢN LÝ LOẠI MÓN ĂN");

        tblLoaiMonAn.setBackground(new java.awt.Color(0, 255, 204));
        tblLoaiMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ LOẠI MÓN", "TÊN LOẠI MÓN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiMonAn.setRowHeight(30);
        tblLoaiMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiMonAnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLoaiMonAn);

        jLabel26.setBackground(new java.awt.Color(51, 51, 51));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("MÓN ĂN");

        tblMonAnChung.setBackground(new java.awt.Color(0, 255, 204));
        tblMonAnChung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ MÓN ĂN", "TÊN MÓN ĂN", "TÊN LOẠI MÓN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonAnChung.setRowHeight(30);
        jScrollPane3.setViewportView(tblMonAnChung);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel25)
                        .addGap(0, 219, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))))
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(153, 255, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Loại món:");

        btnXoa1.setBackground(new java.awt.Color(102, 102, 102));
        btnXoa1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa1.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoa.png"))); // NOI18N
        btnXoa1.setText("Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        txtMaLoaiMon.setBackground(new java.awt.Color(153, 255, 204));
        txtMaLoaiMon.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtMaLoaiMon.setText("0");
        txtMaLoaiMon.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtTenLoaiMon.setBackground(new java.awt.Color(153, 255, 204));
        txtTenLoaiMon.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtTenLoaiMon.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnShow.setBackground(new java.awt.Color(102, 102, 102));
        btnShow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShow.setForeground(new java.awt.Color(255, 255, 255));
        btnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lammoi.png"))); // NOI18N
        btnShow.setText(" Show Món Ăn");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Tên loại món:");

        btnLuu1.setBackground(new java.awt.Color(102, 102, 102));
        btnLuu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLuu1.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/luu.png"))); // NOI18N
        btnLuu1.setText("Lưu");
        btnLuu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu1ActionPerformed(evt);
            }
        });

        btnSua1.setBackground(new java.awt.Color(102, 102, 102));
        btnSua1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua1.setForeground(new java.awt.Color(255, 255, 255));
        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sua.png"))); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        txtShowMonAn.setBackground(new java.awt.Color(153, 255, 204));
        txtShowMonAn.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtShowMonAn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtShowMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtShowMonAnMouseReleased(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Mã loại món:");

        btnThem1.setBackground(new java.awt.Color(102, 102, 102));
        btnThem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem1.setForeground(new java.awt.Color(255, 255, 255));
        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(txtShowMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnShow)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaLoaiMon, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(txtTenLoaiMon))))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(btnThem1)
                .addGap(18, 18, 18)
                .addComponent(btnLuu1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtMaLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtTenLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1)
                    .addComponent(btnLuu1)
                    .addComponent(btnSua1)
                    .addComponent(btnXoa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtShowMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnShow)
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("LOẠI MÓN ĂN", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMouseReleased
        search();
    }//GEN-LAST:event_txtTimKiemMouseReleased

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if (ktTimKiem()) {
            search();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void lblHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhAnhMouseClicked
        choosePicture();
    }//GEN-LAST:event_lblHinhAnhMouseClicked

    private void cboTenLoaiMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenLoaiMonActionPerformed
        chonTenLoaiMonAn();
    }//GEN-LAST:event_cboTenLoaiMonActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (kiemTraMon()) {
            updateMon();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if (kiemTraMon()) {
            insertMon();
        }

    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        deleteMon();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        clearFormMon();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        deleteLoai();
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        searchMonChung();
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnLuu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu1ActionPerformed
        if (kiemTraLoai()) {
            insertLoai();
        }
    }//GEN-LAST:event_btnLuu1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        if (kiemTraLoai()) {
            updateLoai();
            fillTableMonChung();
        }
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void txtShowMonAnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtShowMonAnMouseReleased
        searchMonChung();
    }//GEN-LAST:event_txtShowMonAnMouseReleased

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        clearFormLoai();
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void tblMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonAnMouseClicked
        if (evt.getClickCount() == 1) {
            this.row = tblMonAn.getSelectedRow();
            this.editMon();
        }
    }//GEN-LAST:event_tblMonAnMouseClicked

    private void tblLoaiMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiMonAnMouseClicked
        if (evt.getClickCount() == 1) {
            this.row = tblLoaiMonAn.getSelectedRow();
            this.editLoai();
//            fillTableMonChungM();
        }
    }//GEN-LAST:event_tblLoaiMonAnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuu1;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JComboBox<Object> cboTenLoaiMon;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JTable tblLoaiMonAn;
    private javax.swing.JTable tblMonAn;
    private javax.swing.JTable tblMonAnChung;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtMaLoaiMon;
    private javax.swing.JTextField txtMaLoaiMon1;
    private javax.swing.JTextField txtMaMonAn;
    private javax.swing.JTextField txtShowMonAn;
    private javax.swing.JTextField txtTenLoaiMon;
    private javax.swing.JTextField txtTenMonAn;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    LoaiMonAnDAO loaiDao = new LoaiMonAnDAO();
    MonAnDAO mondao = new MonAnDAO();
    JFileChooser fileChooser = new JFileChooser();
    String dong = " đ";
    int row = -1;

    void init() {
        this.fillTableLoai();
        this.fillTableMonChung();
        this.fillTableMon();
        this.updateStatus();
        clearFormLoai();
    }

    // code loại món ăn
    void fillTableLoai() {
        DefaultTableModel model = (DefaultTableModel) tblLoaiMonAn.getModel();
        model.setRowCount(0);
        try {
            List<LoaiMonAn> list = loaiDao.selectAll();
            for (LoaiMonAn loai : list) {
                Object[] rows = {loai.getMaLoaiMonAn(),
                    loai.getTenLoaiMonAn()};
                model.addRow(rows);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy cập dữ liệu!");
        }
    }

    private LoaiMonAn getFormLoai() {
        LoaiMonAn loai = new LoaiMonAn();
        loai.setMaLoaiMonAn(Integer.valueOf(txtMaLoaiMon.getText()));
        loai.setTenLoaiMonAn(txtTenLoaiMon.getText());
        return loai;
    }

    void setFormLoai(LoaiMonAn loai) {
        txtMaLoaiMon.setText(String.valueOf(loai.getMaLoaiMonAn()));
        txtTenLoaiMon.setText(loai.getTenLoaiMonAn());
    }

    void clearFormLoai() {
        LoaiMonAn loai = new LoaiMonAn();
        this.setFormLoai(loai);
        this.row = -1;
        this.updateStatus();
    }

    void insertLoai() {
        LoaiMonAn loai = getFormLoai();
        try {
            loaiDao.insert(loai);
            this.fillTableLoai();
            fillComboBoxMon();
            this.clearFormLoai();
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Mã loại món ăn không được trùng!");
        }
    }

    void updateLoai() {
        LoaiMonAn loai = getFormLoai();
        try {
            loaiDao.update(loai);
            this.fillTableLoai();
            fillComboBoxMon();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    void deleteLoai() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa !");
        } else {
            int id = Integer.valueOf(txtMaLoaiMon.getText());
            if (MsgBox.confirm(this, "Bạn có muốn xóa hay không?")) {
                try {
                    loaiDao.delete(id);
                    this.fillTableLoai();
                    fillComboBoxMon();
                    this.clearFormLoai();
                    MsgBox.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại vì sản phẩm có trong hóa đơn!");
                }
            }
        }
    }

    void editLoai() {
        int loaiMon = (Integer) tblLoaiMonAn.getValueAt(this.row, 0);
        LoaiMonAn loai = loaiDao.selectById(loaiMon);
        this.setFormLoai(loai);
        this.updateStatus();
    }

    // code món ăn
    void fillTableMon() {
        DefaultTableModel model = (DefaultTableModel) tblMonAn.getModel();
        model.setRowCount(0);
        try {
            List<MonAn> list = mondao.selectAllWithLoai();
            for (MonAn mon : list) {
                Object[] rows = {mon.getMaMonAn(),
                    mon.getTenMonAn(),
                    mon.getTenLoaiMonAn(),
                    mon.getGiaTien() + dong,
                    mon.getHinhAnh()};
                model.addRow(rows);
            }
            fillComboBoxMon();
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy cập dữ liệu!");
        }
    }

    void fillComboBoxMon() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenLoaiMon.getModel();
        model.removeAllElements();
        List<LoaiMonAn> list = loaiDao.selectAll();
        for (LoaiMonAn loai : list) {
            model.addElement(loai);
        }
    }

    void fillComboBoxMon1() {
        String tenloai = (String) tblMonAn.getValueAt(row, 2);
        int i = 0;
        while (true) {
            String nameform = cboTenLoaiMon.getItemAt(i).toString();
            if (nameform.equalsIgnoreCase(tenloai)) {
                cboTenLoaiMon.setSelectedIndex(i);
                break;
            }
            i++;
        }
    }

    void choosePicture() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            fileChooser.setDialogTitle("Choose Image");
            File file = fileChooser.getSelectedFile();
            XImage.saveMon(file);
            ImageIcon icon = XImage.readMon(file.getName());
            lblHinhAnh.setToolTipText(file.getName());
            lblHinhAnh.setIcon(icon);
        }
    }

    void chonTenLoaiMonAn() {
        LoaiMonAn loai = (LoaiMonAn) cboTenLoaiMon.getSelectedItem();
        if (loai != null) {
            txtMaLoaiMon1.setText(String.valueOf(loai.getMaLoaiMonAn()));
        }
    }

    private MonAn getFormMon() {
        MonAn mon = new MonAn();
        mon.setMaMonAn(Integer.valueOf(txtMaMonAn.getText()));
        mon.setTenMonAn(txtTenMonAn.getText());
        LoaiMonAn loai = (LoaiMonAn) cboTenLoaiMon.getSelectedItem();
        mon.setMaLoaiMonAn(loai.getMaLoaiMonAn());
        mon.setGiaTien(Float.parseFloat(txtGiaTien.getText()));
        mon.setHinhAnh(lblHinhAnh.getToolTipText());
        return mon;
    }

    void setFormMon(MonAn mon) {
        txtMaMonAn.setText(String.valueOf(mon.getMaMonAn()));
        txtTenMonAn.setText(mon.getTenMonAn());
        txtGiaTien.setText(String.valueOf(mon.getGiaTien()));
        if (mon.getHinhAnh() != null) {
            lblHinhAnh.setToolTipText(mon.getHinhAnh());
            lblHinhAnh.setIcon(XImage.readMon(mon.getHinhAnh()));
        }
    }

    void insertMon() {
        MonAn monAn = getFormMon();
        if (lblHinhAnh.getToolTipText() == null) {
            MsgBox.alert(this, "Hình ảnh không được để trống!");
        } else {
            try {
                mondao.insert(monAn);
                this.fillTableMon();
                clearFormMon();
                MsgBox.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Mã món ăn không được trùng!");
            }
        }
    }

    void updateMon() {
        MonAn monAn = getFormMon();
        try {
            mondao.update(monAn);
            this.fillTableMon();
            clearFormMon();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    void clearFormMon() {
        MonAn monAn = new MonAn();
        lblHinhAnh.setIcon(null);
        cboTenLoaiMon.setSelectedIndex(0);
        this.setFormMon(monAn);
        this.row = -1;
        this.updateStatus();
    }

    void deleteMon() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa món ăn!");
        } else {
            String id = txtMaMonAn.getText();
            if (MsgBox.confirm(this, "Bạn có muốn xóa hay không?")) {
                try {
                    mondao.delete(Integer.valueOf(id));
                    this.fillTableMon();
//                this.clearFormMon();
                    MsgBox.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại!");
                }
            }
        }
    }

    void editMon() {
        int maMon = (int) tblMonAn.getValueAt(this.row, 0);
        MonAn mon = mondao.selectByIdWithMon(maMon);
        fillComboBoxMon1();
        this.setFormMon(mon);
        this.updateStatus();
    }

    void fillTableMon1() {
        DefaultTableModel model = (DefaultTableModel) tblMonAn.getModel();
        model.setRowCount(0);
        try {
            String tenMon = txtTimKiem.getText();
            List<MonAn> list = mondao.selectTenMon(tenMon);
            for (MonAn mon : list) {
                Object[] rows = {mon.getMaMonAn(),
                    mon.getTenMonAn(),
                    mon.getTenLoaiMonAn(),
                    mon.getGiaTien() + dong,
                    mon.getHinhAnh()};
                model.addRow(rows);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy cập dữ liệu tìm kiếm!");
        }
    }

    void search() {
        this.fillTableMon1();
        this.clearFormMon();
        this.row = -1;
        this.updateStatus();
    }

    void fillTableMonChung() {
        DefaultTableModel model = (DefaultTableModel) tblMonAnChung.getModel();
        model.setRowCount(0);
        try {
            String tenMon = txtShowMonAn.getText();
            List<MonAn> list = mondao.selectTenMon(tenMon);
            for (MonAn mon : list) {
                Object[] rows = {mon.getMaMonAn(),
                    mon.getTenMonAn(),
                    mon.getTenLoaiMonAn()};
                model.addRow(rows);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy cập dữ liệu!");
        }
    }

    void fillTableMonChungM() {
        DefaultTableModel model = (DefaultTableModel) tblMonAnChung.getModel();
        model.setRowCount(0);
        try {
            String TenLoai = txtShowMonAn.getText();
            List<MonAn> list = mondao.selectTenLoaiLoai(TenLoai);
            for (MonAn mon : list) {
                Object[] rows = {mon.getMaMonAn(),
                    mon.getTenMonAn(),
                    mon.getTenLoaiMonAn()};
                model.addRow(rows);
            }
        } catch (Exception e) {
//            MsgBox.alert(this, "Lỗi truy cập dữ liệu!");
        }
    }

    void searchMonChung() {
        fillTableMonChungM();
        this.row = -1;
    }

    //Trạng thái
    void updateStatus() {
        boolean edit = (this.row >= 0);
        //trạng thái form
        //Loại
        txtMaLoaiMon.enable(false);
        btnLuu1.setEnabled(!edit);
        btnSua1.setEnabled(edit);
        btnXoa1.setEnabled(edit);
        //Món
        txtMaMonAn.enable(false);
        txtMaLoaiMon1.enable(false);
        btnLuu.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
    }

    boolean kiemTraMon() {
        if (txtTenMonAn.getText().trim().length() == 0) {
            MsgBox.alert(this, "Tên món không được để trống!");
            txtTimKiem.requestFocus();
            return false;
        }
        if (txtGiaTien.getText().trim().length() == 0) {
            MsgBox.alert(this, "Giá tiền không được để trống!");
            txtGiaTien.requestFocus();
            return false;
        }
        try {
            double giaien = Double.parseDouble(txtGiaTien.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Giá tiền phải là số !");
            txtGiaTien.setText("");
            txtGiaTien.requestFocus();
            return false;
        }
        return true;
    }

    boolean ktTimKiem() {
        if (txtTimKiem.getText().trim().length() == 0) {
            MsgBox.alert(this, "Bạn chưa nhập tên muốn tìm!");
            txtTimKiem.requestFocus();
            return false;
        }
        return true;
    }

    boolean kiemTraLoai() {
        if (txtTenLoaiMon.getText().trim().length() == 0) {
            MsgBox.alert(this, "Tên loại món không được để trống!");
            txtTenLoaiMon.requestFocus();
            return false;
        }
        return true;
    }
}
